<script>
  import { onMount } from "svelte";
  import Alert from "../../components/Alert.svelte";

  let file;
  let code = "";
  let alertVisible = false;
  let alertMessage = "";
  let alertType = "info";

  async function sendFile() {
    const formData = new FormData();
    formData.append("file", file);
    formData.append("code", code); // Include code generated by the sender

    try {
      const response = await fetch("http://127.0.0.1:5000/send", {
        method: "POST",
        body: formData,
      });

      if (response.ok) {
        alertMessage = "File sent successfully!"; // Set alert message
        alertType = "success"; // Set alert type
        alertVisible = true; // Show alert
        file = null; // Clear the file input
        code = generateRandomCode(); // Generate a new random code
      } else {
        const error = await response.json();
        alertMessage = "Error: " + error.message; // Set error message
        alertType = "error"; // Set alert type
        alertVisible = true; // Show alert
      }
    } catch (error) {
      alertMessage = "Error: " + error.message; // Set error message
      alertType = "error"; // Set alert type
      alertVisible = true; // Show alert
    }
    console.log("Sending file:", file);
    console.log("Using code:", code);
  }

  function handleFileChange(event) {
    file = event.target.files[0];
    console.log("Selected file:", file);
  }

  onMount(() => {
    code = generateRandomCode(); // Call a function to generate random code
  });

  function generateRandomCode() {
    const characters =
      "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    let code = "";
    for (let i = 0; i < 6; i++) {
      code += characters.charAt(Math.floor(Math.random() * characters.length));
    }
    return code;
  }
</script>

<div class="sender-container">
  <h2>Upload a File</h2>
  <input type="file" on:change={handleFileChange} />
  <p>{code}</p>
  <button on:click={sendFile}>Send</button>

  <!-- Use the Alert component -->
  <Alert message={alertMessage} type={alertType} visible={alertVisible} />
</div>

<style>
  * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }

  * {
    background-color: black;
    color: white;
  }

  .sender-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    height: 100vh;
    background-color: black;
    color: white;
  }

  h2 {
    margin-bottom: 20px;
  }

  input[type="file"] {
    padding: 10px;
    border: 1px solid white;
    border-radius: 5px;
    background-color: #333;
    color: white;
    width: 200px;
    margin-bottom: 10px;
  }

  button {
    margin-top: 10px;
    padding: 10px 20px;
    border: none;
    border-radius: 5px;
    background-color: white;
    color: black;
    cursor: pointer;
    transition: background-color 0.3s;
  }

  button:hover {
    background-color: #ddd;
  }
</style>
